git:
  depth: false
dist: focal
before_install:
  - sudo apt-get update
  - sudo apt-get upgrade -yy
  - sudo apt-get dist-upgrade -yy
  - sudo apt-get install -y python3 make g++ libjansson-dev python3-pygit2
language: minimal
script:
  - |
    wget https://github.com/milasudril/maike/releases/download/untagged-2cbed9690c80f6801e6e/maike-src.tar.gz
    tar -xf maike-src.tar.gz
    cd maike-src
    make
    sudo make install
    cd ..
    sudo rm -rf maike-src
    ls
    make bootstrap-test

# TODO   sudo ./install /usr/local
# TODO   make bootstrap
