git:
  depth: false
dist: focal
before_install:
  - sudo apt-get update
  - sudo apt-get upgrade -yy
  - sudo apt-get dist-upgrade -yy
  - sudo apt-get install -y python3 make g++ libjansson-dev ronn python3-pygit2
language: minimal
script:
  - |
    wget https://github.com/milasudril/maike/releases/download/0.24.0/maike-src.tar.gz
    tar -xf maike-src.tar.gz
    cd maike-src
    make
    sudo ./install /usr/local
    cd ..
    sudo rm -rf maike-src
    ls
    make bootstrap-test

# TODO   sudo ./install /usr/local
# TODO   make bootstrap
