mkdir '__targets'
mkdir '__targets/targetcxx'
'g++' '-E' '-dM' '-x' 'c++' '/dev/null'
'g++' '-c' '-g' '-fpic' '-std=c++11' '-Wall' '-Woverflow' '-Wconversion' '-Werror' '-o' '__targets/stringformat.o' 'stringformat.cpp'
'g++' '-c' '-g' '-fpic' '-std=c++11' '-Wall' '-Woverflow' '-Wconversion' '-Werror' '-o' '__targets/errormessage.o' 'errormessage.cpp'
'g++' '-c' '-g' '-fpic' '-std=c++11' '-Wall' '-Woverflow' '-Wconversion' '-Werror' '-o' '__targets/exceptionhandler.o' 'exceptionhandler.cpp'
'g++' '-c' '-g' '-fpic' '-std=c++11' '-Wall' '-Woverflow' '-Wconversion' '-Werror' '-o' '__targets/strerror.o' 'strerror-posix.cpp'
'g++' '-c' '-g' '-fpic' '-std=c++11' '-Wall' '-Woverflow' '-Wconversion' '-Werror' '-o' '__targets/fileout.o' 'fileout-posix.cpp'
'g++' '-c' '-g' '-fpic' '-std=c++11' '-Wall' '-Woverflow' '-Wconversion' '-Werror' '-o' '__targets/stdstream.o' 'stdstream.cpp'
'g++' '-c' '-g' '-fpic' '-std=c++11' '-Wall' '-Woverflow' '-Wconversion' '-Werror' '-o' '__targets/writebuffer.o' 'writebuffer.cpp'
'g++' '-c' '-g' '-fpic' '-std=c++11' '-Wall' '-Woverflow' '-Wconversion' '-Werror' '-o' '__targets/pipe.o' 'pipe-posix.cpp'
'g++' '-c' '-g' '-fpic' '-std=c++11' '-Wall' '-Woverflow' '-Wconversion' '-Werror' '-o' '__targets/resourceobject.o' 'resourceobject.cpp'
'g++' '-c' '-g' '-fpic' '-std=c++11' '-Wall' '-Woverflow' '-Wconversion' '-Werror' '-o' '__targets/command.o' 'command.cpp'
'g++' '-c' '-g' '-fpic' '-std=c++11' '-Wall' '-Woverflow' '-Wconversion' '-Werror' '-o' '__targets/targetcxx/targetcxxoptions.o' 'targetcxx/targetcxxoptions.cpp'
'g++' '-c' '-g' '-fpic' '-std=c++11' '-Wall' '-Woverflow' '-Wconversion' '-Werror' '-o' '__targets/targetcxx/targetcxxpptokenizer.o' 'targetcxx/targetcxxpptokenizer.cpp'
'g++' '-c' '-g' '-fpic' '-std=c++11' '-Wall' '-Woverflow' '-Wconversion' '-Werror' '-o' '__targets/pathutils.o' 'pathutils.cpp'
'g++' '-c' '-g' '-fpic' '-std=c++11' '-Wall' '-Woverflow' '-Wconversion' '-Werror' '-o' '__targets/dependency.o' 'dependency.cpp'
'g++' '-c' '-g' '-fpic' '-std=c++11' '-Wall' '-Woverflow' '-Wconversion' '-Werror' '-o' '__targets/filein.o' 'filein-posix.cpp'
'g++' '-c' '-g' '-fpic' '-std=c++11' '-Wall' '-Woverflow' '-Wconversion' '-Werror' '-o' '__targets/fileutils.o' 'fileutils-linuxgnu.cpp'
'g++' '-c' '-g' '-fpic' '-std=c++11' '-Wall' '-Woverflow' '-Wconversion' '-Werror' '-o' '__targets/thread.o' 'thread-posix.cpp'
'g++' '-c' '-g' '-fpic' '-std=c++11' '-Wall' '-Woverflow' '-Wconversion' '-Werror' '-o' '__targets/targetcxx/targetcxxcompiler.o' 'targetcxx/targetcxxcompiler.cpp'
'g++' '-c' '-g' '-fpic' '-std=c++11' '-Wall' '-Woverflow' '-Wconversion' '-Werror' '-o' '__targets/targetcxx/targetcxxloader.o' 'targetcxx/targetcxxloader.cpp'
'g++' '-c' '-g' '-fpic' '-std=c++11' '-Wall' '-Woverflow' '-Wconversion' '-Werror' '-o' '__targets/timedscope.o' 'timedscope-linux.cpp'
'g++' '-c' '-g' '-fpic' '-std=c++11' '-Wall' '-Woverflow' '-Wconversion' '-Werror' '-o' '__targets/targetbase.o' 'targetbase.cpp'
'g++' '-c' '-g' '-fpic' '-std=c++11' '-Wall' '-Woverflow' '-Wconversion' '-Werror' '-o' '__targets/targetcxx/targetcxxpkgconfig.o' 'targetcxx/targetcxxpkgconfig.cpp'
'g++' '-c' '-g' '-fpic' '-std=c++11' '-Wall' '-Woverflow' '-Wconversion' '-Werror' '-o' '__targets/targetcxx/targetcxx.o' 'targetcxx/targetcxx.cpp'
'g++' '-c' '-g' '-fpic' '-std=c++11' '-Wall' '-Woverflow' '-Wconversion' '-Werror' '-o' '__targets/targetcxx/targetcxxfactory.o' 'targetcxx/targetcxxfactory.cpp'
'g++' '-c' '-g' '-fpic' '-std=c++11' '-Wall' '-Woverflow' '-Wconversion' '-Werror' '-o' '__targets/targetcxx/targetcxxhook.o' 'targetcxx/targetcxxhook.cpp'
'g++' '-g' '-fpic' '-std=c++11' '-Wall' '-Woverflow' '-Wconversion' '-Werror' '-shared' '-o' '__targets/targetcxx.so' 'targetcxx/targetcxxmain.cpp' '__targets/targetcxx/targetcxxhook.o' '__targets/targetcxx/targetcxxfactory.o' '__targets/targetcxx/targetcxx.o' '__targets/targetcxx/targetcxxpkgconfig.o' '__targets/targetbase.o' '__targets/timedscope.o' '__targets/targetcxx/targetcxxloader.o' '__targets/targetcxx/targetcxxcompiler.o' '__targets/thread.o' '-lpthread' '__targets/fileutils.o' '__targets/filein.o' '__targets/dependency.o' '__targets/pathutils.o' '__targets/targetcxx/targetcxxpptokenizer.o' '__targets/targetcxx/targetcxxoptions.o' '__targets/command.o' '__targets/resourceobject.o' '-ljansson' '__targets/pipe.o' '__targets/writebuffer.o' '__targets/stdstream.o' '__targets/fileout.o' '__targets/strerror.o' '__targets/exceptionhandler.o' '__targets/errormessage.o' '__targets/stringformat.o'
'g++' '-c' '-g' '-fpic' '-std=c++11' '-Wall' '-Woverflow' '-Wconversion' '-Werror' '-o' '__targets/fileinfo.o' 'fileinfo-linuxgnu.cpp'
'g++' '-g' '-fpic' '-std=c++11' '-Wall' '-Woverflow' '-Wconversion' '-Werror' '-o' '__targets/wand2maike' 'wand2maike.cpp' '__targets/resourceobject.o' '-ljansson' '__targets/pathutils.o' '__targets/fileinfo.o' '__targets/fileutils.o' '__targets/filein.o' '__targets/writebuffer.o' '__targets/stdstream.o' '__targets/fileout.o' '__targets/strerror.o' '__targets/exceptionhandler.o' '__targets/errormessage.o' '__targets/stringformat.o'
'python3' '--' 'maikeinfo.py' '__targets'
'g++' '-c' '-g' '-fpic' '-std=c++11' '-Wall' '-Woverflow' '-Wconversion' '-Werror' '-o' '__targets/maikeinfo.o' '__targets/maikeinfo.cpp'
'g++' '-c' '-g' '-fpic' '-std=c++11' '-Wall' '-Woverflow' '-Wconversion' '-Werror' '-o' '__targets/versionnumber.o' 'versionnumber.cpp'
'g++' '-c' '-g' '-fpic' '-std=c++11' '-Wall' '-Woverflow' '-Wconversion' '-Werror' '-o' '__targets/sysvars.o' 'sysvars-linux.cpp'
'g++' '-c' '-g' '-fpic' '-std=c++11' '-Wall' '-Woverflow' '-Wconversion' '-Werror' '-o' '__targets/systemtargetinfo.o' 'systemtargetinfo.cpp'
'g++' '-c' '-g' '-fpic' '-std=c++11' '-Wall' '-Woverflow' '-Wconversion' '-Werror' '-o' '__targets/directorylister.o' 'directorylister-linuxgnu.cpp'
'g++' '-c' '-g' '-fpic' '-std=c++11' '-Wall' '-Woverflow' '-Wconversion' '-Werror' '-o' '__targets/targetdirectory.o' 'targetdirectory.cpp'
'g++' '-c' '-g' '-fpic' '-std=c++11' '-Wall' '-Woverflow' '-Wconversion' '-Werror' '-o' '__targets/targetdirectoryloader.o' 'targetdirectoryloader.cpp'
'g++' '-c' '-g' '-fpic' '-std=c++11' '-Wall' '-Woverflow' '-Wconversion' '-Werror' '-o' '__targets/expressionevaluator.o' 'expressionevaluator.cpp'
'g++' '-c' '-g' '-fpic' '-std=c++11' '-Wall' '-Woverflow' '-Wconversion' '-Werror' '-o' '__targets/spiderdefault.o' 'spiderdefault.cpp'
'g++' '-c' '-g' '-fpic' '-std=c++11' '-Wall' '-Woverflow' '-Wconversion' '-Werror' '-o' '__targets/dependencygraphdefault.o' 'dependencygraphdefault.cpp'
'g++' '-c' '-g' '-fpic' '-std=c++11' '-Wall' '-Woverflow' '-Wconversion' '-Werror' '-o' '__targets/plugin.o' 'plugin-linuxgnu.cpp'
'g++' '-c' '-g' '-fpic' '-std=c++11' '-Wall' '-Woverflow' '-Wconversion' '-Werror' '-o' '__targets/target_hook_plugin.o' 'target_hook_plugin.cpp'
'g++' '-c' '-g' '-fpic' '-std=c++11' '-Wall' '-Woverflow' '-Wconversion' '-Werror' '-o' '__targets/target_hook_registry.o' 'target_hook_registry.cpp'
'g++' '-c' '-g' '-fpic' '-std=c++11' '-Wall' '-Woverflow' '-Wconversion' '-Werror' '-o' '__targets/target_factorydelegatordefault.o' 'target_factorydelegatordefault.cpp'
'g++' '-c' '-g' '-fpic' '-std=c++11' '-Wall' '-Woverflow' '-Wconversion' '-Werror' '-o' '__targets/session.o' 'session.cpp'
'g++' '-c' '-g' '-fpic' '-std=c++11' '-Wall' '-Woverflow' '-Wconversion' '-Werror' '-o' '__targets/maike.o' 'maike.cpp'
'ar' 'rcs' '__targets/libmaike.a' '__targets/maike.o' '__targets/session.o' '__targets/target_factorydelegatordefault.o' '__targets/target_hook_registry.o' '__targets/target_hook_plugin.o' '__targets/plugin.o' '__targets/dependencygraphdefault.o' '__targets/spiderdefault.o' '__targets/expressionevaluator.o' '__targets/targetdirectoryloader.o' '__targets/targetdirectory.o' '__targets/fileutils.o' '__targets/writebuffer.o' '__targets/stdstream.o' '__targets/fileout.o' '__targets/fileinfo.o' '__targets/directorylister.o' '__targets/systemtargetinfo.o' '__targets/sysvars.o' '__targets/filein.o' '__targets/strerror.o' '__targets/versionnumber.o' '__targets/targetbase.o' '__targets/timedscope.o' '__targets/dependency.o' '__targets/pathutils.o' '__targets/resourceobject.o' '__targets/maikeinfo.o' '__targets/exceptionhandler.o' '__targets/errormessage.o' '__targets/stringformat.o'
grep -v '^[[:space:]]*//@' 'visibility.hpp' > '__targets/visibility.hpp'
grep -v '^[[:space:]]*//@' 'exceptionhandler.hpp' > '__targets/exceptionhandler.hpp'
grep -v '^[[:space:]]*//@' 'twins.hpp' > '__targets/twins.hpp'
grep -v '^[[:space:]]*//@' 'maike_static.hpp' > '__targets/maike_static.hpp'
grep -v '^[[:space:]]*//@' 'datasource.hpp' > '__targets/datasource.hpp'
grep -v '^[[:space:]]*//@' 'datasink.hpp' > '__targets/datasink.hpp'
grep -v '^[[:space:]]*//@' 'resourceobject.hpp' > '__targets/resourceobject.hpp'
grep -v '^[[:space:]]*//@' 'graphedgewriter.hpp' > '__targets/graphedgewriter.hpp'
grep -v '^[[:space:]]*//@' 'errormessage.hpp' > '__targets/errormessage.hpp'
grep -v '^[[:space:]]*//@' 'maike.hpp' > '__targets/maike.hpp'
mkdir '__targets/targetpython'
'g++' '-c' '-g' '-fpic' '-std=c++11' '-Wall' '-Woverflow' '-Wconversion' '-Werror' '-o' '__targets/targetpython/targetpythoninterpreter.o' 'targetpython/targetpythoninterpreter.cpp'
'g++' '-c' '-g' '-fpic' '-std=c++11' '-Wall' '-Woverflow' '-Wconversion' '-Werror' '-o' '__targets/targetpython/targetpythonloader.o' 'targetpython/targetpythonloader.cpp'
'g++' '-c' '-g' '-fpic' '-std=c++11' '-Wall' '-Woverflow' '-Wconversion' '-Werror' '-o' '__targets/targetpython/targetpython.o' 'targetpython/targetpython.cpp'
'g++' '-c' '-g' '-fpic' '-std=c++11' '-Wall' '-Woverflow' '-Wconversion' '-Werror' '-o' '__targets/targetpython/targetpythonfactory.o' 'targetpython/targetpythonfactory.cpp'
'g++' '-c' '-g' '-fpic' '-std=c++11' '-Wall' '-Woverflow' '-Wconversion' '-Werror' '-o' '__targets/targetpython/targetpythonhook.o' 'targetpython/targetpythonhook.cpp'
'g++' '-g' '-fpic' '-std=c++11' '-Wall' '-Woverflow' '-Wconversion' '-Werror' '-shared' '-o' '__targets/targetpython.so' 'targetpython/targetpythonmain.cpp' '__targets/targetpython/targetpythonhook.o' '__targets/targetpython/targetpythonfactory.o' '__targets/targetpython/targetpython.o' '__targets/targetbase.o' '__targets/timedscope.o' '__targets/dependency.o' '__targets/pathutils.o' '__targets/targetpython/targetpythonloader.o' '__targets/filein.o' '__targets/targetpython/targetpythoninterpreter.o' '__targets/thread.o' '-lpthread' '__targets/command.o' '__targets/resourceobject.o' '-ljansson' '__targets/pipe.o' '__targets/writebuffer.o' '__targets/stdstream.o' '__targets/fileout.o' '__targets/strerror.o' '__targets/exceptionhandler.o' '__targets/errormessage.o' '__targets/stringformat.o'
grep -v '^[[:space:]]*//@' 'target.hpp' > '__targets/target.hpp'
grep -v '^[[:space:]]*//@' 'dependency.hpp' > '__targets/dependency.hpp'
grep -v '^[[:space:]]*//@' 'target_hook.hpp' > '__targets/target_hook.hpp'
grep -v '^[[:space:]]*//@' 'targetbase.hpp' > '__targets/targetbase.hpp'
grep -v '^[[:space:]]*//@' 'handle.hpp' > '__targets/handle.hpp'
grep -v '^[[:space:]]*//@' 'pipe.hpp' > '__targets/pipe.hpp'
grep -v '^[[:space:]]*//@' 'fileutils.hpp' > '__targets/fileutils.hpp'
grep -v '^[[:space:]]*//@' 'thread.hpp' > '__targets/thread.hpp'
grep -v '^[[:space:]]*//@' 'command.hpp' > '__targets/command.hpp'
grep -v '^[[:space:]]*//@' 'stdstream.hpp' > '__targets/stdstream.hpp'
grep -v '^[[:space:]]*//@' 'filein.hpp' > '__targets/filein.hpp'
grep -v '^[[:space:]]*//@' 'fileout.hpp' > '__targets/fileout.hpp'
grep -v '^[[:space:]]*//@' 'readbuffer.hpp' > '__targets/readbuffer.hpp'
grep -v '^[[:space:]]*//@' 'writebuffer.hpp' > '__targets/writebuffer.hpp'
grep -v '^[[:space:]]*//@' 'parameterset.hpp' > '__targets/parameterset.hpp'
grep -v '^[[:space:]]*//@' 'stringkey.hpp' > '__targets/stringkey.hpp'
grep -v '^[[:space:]]*//@' 'mapfixed.hpp' > '__targets/mapfixed.hpp'
grep -v '^[[:space:]]*//@' 'parametersetmapfixed.hpp' > '__targets/parametersetmapfixed.hpp'
grep -v '^[[:space:]]*//@' 'variant.hpp' > '__targets/variant.hpp'
grep -v '^[[:space:]]*//@' 'stringformat.hpp' > '__targets/stringformat.hpp'
grep -v '^[[:space:]]*//@' 'spider.hpp' > '__targets/spider.hpp'
grep -v '^[[:space:]]*//@' 'target_factorydelegator.hpp' > '__targets/target_factorydelegator.hpp'
grep -v '^[[:space:]]*//@' 'target_factory.hpp' > '__targets/target_factory.hpp'
grep -v '^[[:space:]]*//@' 'target_loader.hpp' > '__targets/target_loader.hpp'
grep -v '^[[:space:]]*//@' 'libmaikeplug.cpp' > '__targets/maikeplug.hpp'
'ar' 'rcs' '__targets/libmaikeplug.a' '__targets/command.o' '__targets/thread.o' '__targets/fileutils.o' '__targets/filein.o' '__targets/pipe.o' '__targets/writebuffer.o' '__targets/stdstream.o' '__targets/fileout.o' '__targets/strerror.o' '__targets/targetbase.o' '__targets/timedscope.o' '__targets/dependency.o' '__targets/pathutils.o' '__targets/resourceobject.o' '__targets/exceptionhandler.o' '__targets/errormessage.o' '__targets/stringformat.o'
'g++' '-g' '-fpic' '-std=c++11' '-Wall' '-Woverflow' '-Wconversion' '-Werror' '-o' '__targets/pathutils-test' 'pathutils-test.cpp' '__targets/pathutils.o' '__targets/exceptionhandler.o' '__targets/errormessage.o' '__targets/stringformat.o'
'g++' '-c' '-g' '-fpic' '-std=c++11' '-Wall' '-Woverflow' '-Wconversion' '-Werror' '-o' '__targets/options.o' 'options.cpp'
'g++' '-c' '-g' '-fpic' '-std=c++11' '-Wall' '-Woverflow' '-Wconversion' '-Werror' '-o' '__targets/graphedgewriterdot.o' 'graphedgewriterdot.cpp'
'g++' '-g' '-fpic' '-std=c++11' '-Wall' '-Woverflow' '-Wconversion' '-Werror' '-o' '__targets/maike' 'maike-main.cpp' '__targets/graphedgewriterdot.o' '__targets/maike.o' '__targets/session.o' '__targets/target_factorydelegatordefault.o' '__targets/target_hook_registry.o' '__targets/target_hook_plugin.o' '__targets/plugin.o' '-ldl' '__targets/dependencygraphdefault.o' '__targets/spiderdefault.o' '__targets/expressionevaluator.o' '__targets/targetdirectoryloader.o' '__targets/targetdirectory.o' '__targets/fileutils.o' '__targets/stdstream.o' '__targets/fileinfo.o' '__targets/directorylister.o' '__targets/systemtargetinfo.o' '__targets/sysvars.o' '__targets/versionnumber.o' '__targets/targetbase.o' '__targets/timedscope.o' '__targets/dependency.o' '__targets/pathutils.o' '__targets/maikeinfo.o' '__targets/resourceobject.o' '-ljansson' '__targets/filein.o' '__targets/fileout.o' '__targets/strerror.o' '__targets/options.o' '__targets/writebuffer.o' '__targets/exceptionhandler.o' '__targets/errormessage.o' '__targets/stringformat.o'
'g++' '-g' '-fpic' '-std=c++11' '-Wall' '-Woverflow' '-Wconversion' '-Werror' '-shared' '-o' '__targets/libmaike.so' 'libmaike.cpp' '__targets/maike.o' '__targets/session.o' '__targets/target_factorydelegatordefault.o' '__targets/target_hook_registry.o' '__targets/target_hook_plugin.o' '__targets/plugin.o' '-ldl' '__targets/dependencygraphdefault.o' '__targets/spiderdefault.o' '__targets/expressionevaluator.o' '__targets/targetdirectoryloader.o' '__targets/targetdirectory.o' '__targets/fileutils.o' '__targets/writebuffer.o' '__targets/stdstream.o' '__targets/fileout.o' '__targets/fileinfo.o' '__targets/directorylister.o' '__targets/systemtargetinfo.o' '__targets/sysvars.o' '__targets/filein.o' '__targets/strerror.o' '__targets/versionnumber.o' '__targets/targetbase.o' '__targets/timedscope.o' '__targets/dependency.o' '__targets/pathutils.o' '__targets/resourceobject.o' '-ljansson' '__targets/maikeinfo.o' '__targets/exceptionhandler.o' '__targets/errormessage.o' '__targets/stringformat.o'
