@startuml
group Main thread
"Main:LoadSourceFile" -> Loader: getIntrinsicTargets(filename)
return Target names
create InputStream
"Main:LoadSourceFile" -> InputStream: InputFile
"Main:LoadSourceFile" -> Loader: filterTags(InputStream, SourceStream, TagStream)
loop while not eof
Loader -> InputStream: read(buffer, n)
return raw data
Loader -> SourceStream: write(valid source code)
Loader -> TagStream: write(json)
end
"Main:LoadSourceFile" -> SourceStream: stop
"Main:LoadSourceFile" -> TagStream: stop
destroy InputStream
end
group SourceReaderThread
loop while not eof
SourceReader -> SourceStream: read(buffer, n)
return raw data
end
end
group TagReaderTrhead
loop while not eof
TagReader -> "TagStream": read(buffer, n)
return raw data
end
end
group Main thread
"Main:LoadSourceFile" -> "Main:LoadSourceFile":wait(SourceReaderThread)
SourceReader -> "Main:LoadSourceFile": Dependency list
"Main:LoadSourceFile" -> "Main:LoadSourceFile":wait(TagReaderThread)
TagReader -> "Main:LoadSourceFile": Tags
"Main:LoadSourceFile" -> "Main:LoadSourceFile": Associate targets from\nTags with source files
"Main:LoadSourceFile" -> "Main:LoadSourceFile": Associate targets from\nTags with current source file
end
@enduml